apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-manager-csi
  namespace: argocd
spec:
  project: default
  source:
    chart: secrets-store-csi-driver
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    targetRevision: 1.4.8
    helm:
      releaseName: secrets-store-csi-driver
      values: |
        rbac:
          install: true
        syncSecret:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system